openapi: 3.0.3
info:
  title: Play-J Payment Service
  description: Microservice for payment operations
  version: "1.0"
servers:
- url: http://localhost:80
  description: Default server for payment
paths:
  /api/v1/payment-service/payments:
    get:
      tags:
      - payment
      summary: getAccountPayments payment
      operationId: payment#getAccountPayments
      parameters:
      - name: limit
        in: query
        description: Resource array size
        allowEmptyValue: true
        required: true
        schema:
          type: integer
          description: Resource array size
          example: 2004532517057297189
          format: int64
        example: 3763060786574489262
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentListResponse'
              example:
                resources:
                - amount: 0.045109253
                  createdAt: Repudiandae dolores nostrum harum.
                  id: 5614265788585208775
                  paymentNumber: Dolor impedit rerum.
                - amount: 0.045109253
                  createdAt: Repudiandae dolores nostrum harum.
                  id: 5614265788585208775
                  paymentNumber: Dolor impedit rerum.
                total: 6041450981271446607
    post:
      tags:
      - payment
      summary: createAccountPayment payment
      operationId: payment#createAccountPayment
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionResponse'
              example:
                message: Quisquam veniam et maiores dolorem mollitia.
                paymentNumber: Consequatur enim illum aliquam.
  /api/v1/payment-service/subscriptions:
    get:
      tags:
      - subscription
      summary: getAccountSubscriptionStatus subscription
      operationId: subscription#getAccountSubscriptionStatus
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubscriptionStatusResponse'
              example:
                hasPaid: false
                type: Molestiae ipsum cupiditate quis natus adipisci.
                validUntil: Dolorum ab recusandae totam omnis doloremque aperiam.
components:
  schemas:
    PaymentListResponse:
      type: object
      properties:
        resources:
          type: array
          items:
            $ref: '#/components/schemas/PaymentResponse'
          example:
          - amount: 0.045109253
            createdAt: Repudiandae dolores nostrum harum.
            id: 5614265788585208775
            paymentNumber: Dolor impedit rerum.
          - amount: 0.045109253
            createdAt: Repudiandae dolores nostrum harum.
            id: 5614265788585208775
            paymentNumber: Dolor impedit rerum.
          - amount: 0.045109253
            createdAt: Repudiandae dolores nostrum harum.
            id: 5614265788585208775
            paymentNumber: Dolor impedit rerum.
        total:
          type: integer
          example: 9394331883224838666
      example:
        resources:
        - amount: 0.045109253
          createdAt: Repudiandae dolores nostrum harum.
          id: 5614265788585208775
          paymentNumber: Dolor impedit rerum.
        - amount: 0.045109253
          createdAt: Repudiandae dolores nostrum harum.
          id: 5614265788585208775
          paymentNumber: Dolor impedit rerum.
        total: 4728773735449028532
      required:
      - total
      - resources
    PaymentResponse:
      type: object
      properties:
        amount:
          type: number
          example: 0.7131275
          format: float
        createdAt:
          type: string
          example: Vel non quia quo ut quisquam id.
        id:
          type: integer
          example: 12788342778597874420
        paymentNumber:
          type: string
          example: Et qui occaecati ipsum.
      example:
        amount: 0.27847195
        createdAt: Ipsam ullam facere labore ducimus vero.
        id: 12325399110682055005
        paymentNumber: Eaque qui minima.
      required:
      - id
      - createdAt
      - paymentNumber
      - amount
    SubscriptionStatusResponse:
      type: object
      properties:
        hasPaid:
          type: boolean
          description: Is the subscrion paid or not
          example: false
        type:
          type: string
          description: Subscription type
          example: Maiores quam repellat libero porro eum molestiae.
        validUntil:
          type: string
          description: Subscription end date
          example: Iste ipsum sed sequi.
      example:
        hasPaid: true
        type: Exercitationem voluptatum in cupiditate amet cumque.
        validUntil: Consequatur tempore atque possimus aut.
      required:
      - hasPaid
      - validUntil
      - type
    TransactionResponse:
      type: object
      properties:
        message:
          type: string
          description: Operation status
          example: Autem quisquam quae.
        paymentNumber:
          type: string
          description: Payment Unique Number
          example: Repellat et ipsa dignissimos.
      example:
        message: Dolorum est in voluptatem maxime.
        paymentNumber: Cum suscipit dignissimos nisi.
      required:
      - paymentNumber
      - message
tags:
- name: payment
  description: Payment operations
- name: subscription
