swagger: "2.0"
info:
  title: Play-J Payment Service
  description: Microservice for payment operations
  version: ""
host: localhost:80
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /api/v1/payment-service/payments:
    get:
      tags:
      - payment
      summary: getAccountPayments payment
      operationId: payment#getAccountPayments
      parameters:
      - name: limit
        in: query
        description: Resource array size
        required: true
        type: integer
      - name: Authorization
        in: header
        description: JSON Web Token
        required: true
        type: string
        pattern: ^Bearer [^ ]+$
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/PaymentGetAccountPaymentsResponseBody'
            required:
            - total
            - resources
      schemes:
      - http
    post:
      tags:
      - payment
      summary: createAccountPayment payment
      operationId: payment#createAccountPayment
      parameters:
      - name: Authorization
        in: header
        description: JSON Web Token
        required: true
        type: string
        pattern: ^Bearer [^ ]+$
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/PaymentCreateAccountPaymentResponseBody'
            required:
            - paymentNumber
            - message
      schemes:
      - http
  /api/v1/payment-service/subscriptions:
    get:
      tags:
      - subscription
      summary: getAccountSubscriptionStatus subscription
      operationId: subscription#getAccountSubscriptionStatus
      parameters:
      - name: Authorization
        in: header
        description: JSON Web Token
        required: true
        type: string
        pattern: ^Bearer [^ ]+$
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/SubscriptionGetAccountSubscriptionStatusResponseBody'
            required:
            - hasPaid
            - validUntil
            - type
      schemes:
      - http
definitions:
  PaymentCreateAccountPaymentResponseBody:
    title: PaymentCreateAccountPaymentResponseBody
    type: object
    properties:
      message:
        type: string
        description: Operation status
        example: Sed debitis autem eum laboriosam accusantium.
      paymentNumber:
        type: string
        description: Payment Unique Number
        example: Laudantium doloribus ex quisquam velit non.
    example:
      message: Sunt dolores tempore illo vel voluptatum.
      paymentNumber: Provident voluptatem.
    required:
    - paymentNumber
    - message
  PaymentGetAccountPaymentsResponseBody:
    title: PaymentGetAccountPaymentsResponseBody
    type: object
    properties:
      resources:
        type: array
        items:
          $ref: '#/definitions/PaymentResponseResponseBody'
        example:
        - amount: 0.045109253
          createdAt: Repudiandae dolores nostrum harum.
          id: 5614265788585208775
          paymentNumber: Dolor impedit rerum.
        - amount: 0.045109253
          createdAt: Repudiandae dolores nostrum harum.
          id: 5614265788585208775
          paymentNumber: Dolor impedit rerum.
        - amount: 0.045109253
          createdAt: Repudiandae dolores nostrum harum.
          id: 5614265788585208775
          paymentNumber: Dolor impedit rerum.
      total:
        type: integer
        example: 14118431998277998239
        format: int64
    example:
      resources:
      - amount: 0.045109253
        createdAt: Repudiandae dolores nostrum harum.
        id: 5614265788585208775
        paymentNumber: Dolor impedit rerum.
      - amount: 0.045109253
        createdAt: Repudiandae dolores nostrum harum.
        id: 5614265788585208775
        paymentNumber: Dolor impedit rerum.
      total: 17046792413239464317
    required:
    - total
    - resources
  PaymentResponseResponseBody:
    title: PaymentResponseResponseBody
    type: object
    properties:
      amount:
        type: number
        example: 0.65015614
        format: float
      createdAt:
        type: string
        example: Sint esse maxime.
      id:
        type: integer
        example: 9278332640818235837
        format: int64
      paymentNumber:
        type: string
        example: Ut sed vitae.
    example:
      amount: 0.9000871
      createdAt: Omnis est voluptatum blanditiis.
      id: 5149910871047572115
      paymentNumber: Eveniet voluptate eligendi esse iste quia nihil.
    required:
    - id
    - createdAt
    - paymentNumber
    - amount
  SubscriptionGetAccountSubscriptionStatusResponseBody:
    title: SubscriptionGetAccountSubscriptionStatusResponseBody
    type: object
    properties:
      hasPaid:
        type: boolean
        description: Is the subscrion paid or not
        example: true
      type:
        type: string
        description: Subscription type
        example: Velit autem amet perferendis eaque adipisci.
      validUntil:
        type: string
        description: Subscription end date
        example: Ipsa blanditiis ipsam amet aperiam et.
    example:
      hasPaid: true
      type: Provident vel.
      validUntil: Id doloribus qui.
    required:
    - hasPaid
    - validUntil
    - type
