openapi: 3.0.3
info:
  title: Accounts Backend Service
  description: Microservice for account management & operations
  version: "1.0"
servers:
- url: http://localhost:80
  description: Default server for accounts
paths:
  /api/v1/account-service/accounts/login:
    post:
      tags:
      - account
      summary: login account
      operationId: account#login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequestBody'
            example:
              email: Numquam quos excepturi vero ad est.
              password: Ab facilis odio facere et.
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
              example:
                accountID: Molestias exercitationem molestias.
                email: Iusto non mollitia qui non culpa laborum.
                refresh_token: Tempora recusandae nobis.
                role: Reiciendis harum asperiores.
                token: Corrupti voluptas officia nostrum quia voluptatum.
  /api/v1/account-service/accounts/register:
    post:
      tags:
      - account
      summary: register account
      operationId: account#register
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequestBody'
            example:
              confirmedPassword: Cumque quisquam dolorem adipisci.
              email: Nemo provident eos quis ut ut ipsum.
              firstName: Ut magnam et.
              lastName: Vel assumenda eum quibusdam.
              password: Molestiae voluptas dolorum et.
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterResponse'
              example:
                message: Voluptates id recusandae temporibus et dolore.
  /api/v1/account-service/playlists:
    delete:
      tags:
      - playlist
      summary: deleteAccountPlaylist playlist
      operationId: playlist#deleteAccountPlaylist
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeleteAccountPlaylistRequestBody'
            example:
              playlistID: 1690349288743571665
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterResponse'
              example:
                message: Repudiandae cum corporis autem repellendus.
    get:
      tags:
      - playlist
      summary: getAccountPlaylistCollection playlist
      operationId: playlist#getAccountPlaylistCollection
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetAccountPlaylistCollectionRequestBody'
            example:
              accountID: 11324780232132348642
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountPlaylistCollectionResponse'
              example:
                resources:
                - id: 1905447668
                  name: Et quasi sint.
                  trackIDs:
                  - 175494993
                  - 1530977948
                  - 844822519
                  - 1773553620
                - id: 1905447668
                  name: Et quasi sint.
                  trackIDs:
                  - 175494993
                  - 1530977948
                  - 844822519
                  - 1773553620
                - id: 1905447668
                  name: Et quasi sint.
                  trackIDs:
                  - 175494993
                  - 1530977948
                  - 844822519
                  - 1773553620
                total: 1854667561
    post:
      tags:
      - playlist
      summary: createAccountPlaylist playlist
      operationId: playlist#createAccountPlaylist
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAccountPlaylistRequestBody'
            example:
              name: Et enim consectetur.
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterResponse'
              example:
                message: Cupiditate ipsam quis aut commodi id delectus.
  /api/v1/account-service/playlists/{playlistID}:
    get:
      tags:
      - playlist
      summary: getAccountPlaylist playlist
      operationId: playlist#getAccountPlaylist
      parameters:
      - name: playlistID
        in: path
        description: Playlist ID
        required: true
        schema:
          type: integer
          description: Playlist ID
          example: 2675593878929236670
        example: 5594427500673944209
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountPlaylistResponse'
              example:
                id: 482827072
                name: Sed nostrum aut voluptatem sequi adipisci iure.
                trackIDs:
                - 2114708484
                - 1830613622
                - 1175553468
  /api/v1/account-service/playlists/{playlistID}/tracks/{trackID}:
    delete:
      tags:
      - playlist
      summary: removeTrackFromAccountPlaylist playlist
      operationId: playlist#removeTrackFromAccountPlaylist
      parameters:
      - name: playlistID
        in: path
        description: Playlist ID to modify
        required: true
        schema:
          type: integer
          description: Playlist ID to modify
          example: 14403475015437136035
        example: 13634172083196272956
      - name: trackID
        in: path
        description: Track ID to be deleted
        required: true
        schema:
          type: integer
          description: Track ID to be deleted
          example: 171135245237913193
        example: 16198922406143822803
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterResponse'
              example:
                message: Ullam eius.
    post:
      tags:
      - playlist
      summary: addTrackToAccountPlaylist playlist
      operationId: playlist#addTrackToAccountPlaylist
      parameters:
      - name: playlistID
        in: path
        description: Playlist ID to modify
        required: true
        schema:
          type: integer
          description: Playlist ID to modify
          example: 4913374386035097814
        example: 15651613814342603472
      - name: trackID
        in: path
        description: Track ID to be added
        required: true
        schema:
          type: integer
          description: Track ID to be added
          example: 16040897732385780006
        example: 7613700036481937954
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterResponse'
              example:
                message: Quasi modi qui qui.
components:
  schemas:
    AccountPlaylistCollectionResponse:
      type: object
      properties:
        resources:
          type: array
          items:
            $ref: '#/components/schemas/AccountPlaylistResponse'
          description: Operation completion status
          example:
          - id: 1905447668
            name: Et quasi sint.
            trackIDs:
            - 175494993
            - 1530977948
            - 844822519
            - 1773553620
          - id: 1905447668
            name: Et quasi sint.
            trackIDs:
            - 175494993
            - 1530977948
            - 844822519
            - 1773553620
        total:
          type: integer
          description: Number of resources
          example: 1991896056
          format: int32
      example:
        resources:
        - id: 1905447668
          name: Et quasi sint.
          trackIDs:
          - 175494993
          - 1530977948
          - 844822519
          - 1773553620
        - id: 1905447668
          name: Et quasi sint.
          trackIDs:
          - 175494993
          - 1530977948
          - 844822519
          - 1773553620
        total: 1687764714
      required:
      - total
      - resources
    AccountPlaylistResponse:
      type: object
      properties:
        id:
          type: integer
          description: Playlist id
          example: 1540988781
          format: int32
        name:
          type: string
          description: Playlist name
          example: Ipsa quae.
        trackIDs:
          type: array
          items:
            type: integer
            example: 1647847135
            format: int32
          description: Array of TrackIDs
          example:
          - 1535111521
          - 75589077
      example:
        id: 583093875
        name: Doloribus consectetur corporis doloribus autem et ipsa.
        trackIDs:
        - 492043154
        - 94395630
        - 1251627133
        - 1038185886
      required:
      - id
      - name
      - trackIDs
    CreateAccountPlaylistRequestBody:
      type: object
      properties:
        name:
          type: string
          description: Playlist name
          example: Deserunt omnis beatae consequatur explicabo at et.
      example:
        name: Sed ut aut ut.
    DeleteAccountPlaylistRequestBody:
      type: object
      properties:
        playlistID:
          type: integer
          example: 3125244759271945233
      example:
        playlistID: 17097017229226091632
    GetAccountPlaylistCollectionRequestBody:
      type: object
      properties:
        accountID:
          type: integer
          example: 11579680590207708109
      example:
        accountID: 10573761901206515631
    LoginRequestBody:
      type: object
      properties:
        email:
          type: string
          description: Email of the user
          example: Assumenda vel reiciendis et quidem deleniti.
        password:
          type: string
          description: Password of the user
          example: Ducimus eos.
      example:
        email: Qui corporis est debitis.
        password: Nemo dolore dolor impedit explicabo.
    LoginResponse:
      type: object
      properties:
        accountID:
          type: string
          description: User's role
          example: Debitis similique iure.
        email:
          type: string
          description: User's email
          example: Excepturi et alias non sed quam.
        refresh_token:
          type: string
          description: Refresh token
          example: Qui ut.
        role:
          type: string
          description: User's role
          example: Voluptatem nisi molestias consequatur quae.
        token:
          type: string
          description: JWT Token
          example: Animi architecto est perferendis ratione ut.
      example:
        accountID: Enim aut itaque eveniet consequatur.
        email: Et molestiae expedita explicabo ut.
        refresh_token: Aperiam officia rem.
        role: Commodi ut.
        token: Qui consectetur blanditiis nesciunt unde itaque.
      required:
      - email
      - token
      - refresh_token
      - role
    RegisterRequestBody:
      type: object
      properties:
        confirmedPassword:
          type: string
          description: Confirmed password of the user
          example: Et dolor aliquam rem quasi incidunt voluptatem.
        email:
          type: string
          description: Email of the user
          example: Illo libero et.
        firstName:
          type: string
          description: First name of the user
          example: Illum iste iusto aut non.
        lastName:
          type: string
          description: Last name of the user
          example: Maiores illum debitis.
        password:
          type: string
          description: Password of the user
          example: Qui nemo aperiam.
      example:
        confirmedPassword: Officia ut eaque accusantium ullam et quod.
        email: Sed corrupti atque ut beatae id et.
        firstName: Veritatis animi amet dolores odio itaque.
        lastName: Neque officiis assumenda et.
        password: Exercitationem eveniet.
      required:
      - email
      - password
      - confirmedPassword
      - firstName
      - lastName
    RegisterResponse:
      type: object
      properties:
        message:
          type: string
          description: Operation completion status
          example: Doloribus quia vel earum debitis.
      example:
        message: Ut eligendi molestiae velit minus et excepturi.
      required:
      - message
tags:
- name: account
  description: Account operations
- name: playlist
  description: Playlist operations
