swagger: "2.0"
info:
  title: Accounts Backend Service
  description: Microservice for account management & operations
  version: ""
host: localhost:80
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /api/v1/account/{accountID}/playlists:
    get:
      tags:
      - account
      summary: getAccountPlaylistCollection account
      operationId: account#getAccountPlaylistCollection
      parameters:
      - name: accountID
        in: path
        required: true
        type: integer
      - name: Authorization
        in: header
        description: JSON Web Token
        required: false
        type: string
        pattern: ^Bearer [^ ]+$
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/AccountGetAccountPlaylistCollectionResponseBody'
            required:
            - total
            - resources
      schemes:
      - http
    post:
      tags:
      - account
      summary: createAccountPlaylist account
      operationId: account#createAccountPlaylist
      parameters:
      - name: accountID
        in: path
        description: Account ID
        required: true
        type: integer
      - name: Authorization
        in: header
        description: JSON Web Token
        required: false
        type: string
        pattern: ^Bearer [^ ]+$
      - name: CreateAccountPlaylistRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/AccountCreateAccountPlaylistRequestBody'
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/AccountCreateAccountPlaylistResponseBody'
            required:
            - message
      schemes:
      - http
  /api/v1/account/{accountID}/playlists/{playlistID}:
    get:
      tags:
      - account
      summary: getAccountPlaylist account
      operationId: account#getAccountPlaylist
      parameters:
      - name: accountID
        in: path
        description: Account ID
        required: true
        type: integer
      - name: playlistID
        in: path
        description: Playlist ID
        required: true
        type: integer
      - name: Authorization
        in: header
        description: JSON Web Token
        required: false
        type: string
        pattern: ^Bearer [^ ]+$
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/AccountGetAccountPlaylistResponseBody'
            required:
            - id
            - name
            - trackIDs
      schemes:
      - http
    delete:
      tags:
      - account
      summary: deleteAccountPlaylist account
      operationId: account#deleteAccountPlaylist
      parameters:
      - name: accountID
        in: path
        required: true
        type: integer
      - name: playlistID
        in: path
        required: true
        type: integer
      - name: Authorization
        in: header
        description: JSON Web Token
        required: false
        type: string
        pattern: ^Bearer [^ ]+$
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/AccountDeleteAccountPlaylistResponseBody'
            required:
            - message
      schemes:
      - http
  /api/v1/account/{accountID}/playlists/{playlistID}/tracks/{trackID}:
    post:
      tags:
      - account
      summary: addTrackToAccountPlaylist account
      operationId: account#addTrackToAccountPlaylist
      parameters:
      - name: accountID
        in: path
        description: Account ID
        required: true
        type: integer
      - name: playlistID
        in: path
        description: Playlist ID to modify
        required: true
        type: integer
      - name: trackID
        in: path
        description: Track ID to be added
        required: true
        type: integer
      - name: Authorization
        in: header
        description: JSON Web Token
        required: false
        type: string
        pattern: ^Bearer [^ ]+$
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/AccountAddTrackToAccountPlaylistResponseBody'
            required:
            - message
      schemes:
      - http
    delete:
      tags:
      - account
      summary: removeTrackFromAccountPlaylist account
      operationId: account#removeTrackFromAccountPlaylist
      parameters:
      - name: accountID
        in: path
        description: Account ID
        required: true
        type: integer
      - name: playlistID
        in: path
        description: Playlist ID to modify
        required: true
        type: integer
      - name: trackID
        in: path
        description: Track ID to be deleted
        required: true
        type: integer
      - name: Authorization
        in: header
        description: JSON Web Token
        required: false
        type: string
        pattern: ^Bearer [^ ]+$
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/AccountRemoveTrackFromAccountPlaylistResponseBody'
            required:
            - message
      schemes:
      - http
  /api/v1/account/login:
    post:
      tags:
      - account
      summary: login account
      operationId: account#login
      parameters:
      - name: LoginRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/AccountLoginRequestBody'
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/AccountLoginResponseBody'
            required:
            - email
            - token
            - refresh_token
            - role
      schemes:
      - http
  /api/v1/account/register:
    post:
      tags:
      - account
      summary: register account
      operationId: account#register
      parameters:
      - name: RegisterRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/AccountRegisterRequestBody'
          required:
          - email
          - password
          - confirmedPassword
          - firstName
          - lastName
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/AccountRegisterResponseBody'
            required:
            - message
      schemes:
      - http
definitions:
  AccountAddTrackToAccountPlaylistResponseBody:
    title: AccountAddTrackToAccountPlaylistResponseBody
    type: object
    properties:
      message:
        type: string
        description: Operation completion status
        example: Illum iste iusto aut non.
    example:
      message: Maiores illum debitis.
    required:
    - message
  AccountCreateAccountPlaylistRequestBody:
    title: AccountCreateAccountPlaylistRequestBody
    type: object
    properties:
      name:
        type: string
        description: Playlist name
        example: Temporibus ut sequi cupiditate est.
    example:
      name: Fuga quae fuga quia consectetur.
  AccountCreateAccountPlaylistResponseBody:
    title: AccountCreateAccountPlaylistResponseBody
    type: object
    properties:
      message:
        type: string
        description: Operation completion status
        example: Velit quam.
    example:
      message: Magnam et.
    required:
    - message
  AccountDeleteAccountPlaylistResponseBody:
    title: AccountDeleteAccountPlaylistResponseBody
    type: object
    properties:
      message:
        type: string
        description: Operation completion status
        example: Ut sint hic consequatur non.
    example:
      message: Nihil nostrum quo repudiandae.
    required:
    - message
  AccountGetAccountPlaylistCollectionResponseBody:
    title: AccountGetAccountPlaylistCollectionResponseBody
    type: object
    properties:
      resources:
        type: array
        items:
          $ref: '#/definitions/AccountPlaylistResponseResponseBody'
        description: Operation completion status
        example:
        - id: 561047437
          name: Enim consectetur sit omnis expedita.
          trackIDs:
          - 1854591721
          - 551277612
          - 1986047975
        - id: 561047437
          name: Enim consectetur sit omnis expedita.
          trackIDs:
          - 1854591721
          - 551277612
          - 1986047975
      total:
        type: integer
        description: Number of resources
        example: 1794859424
        format: int32
    example:
      resources:
      - id: 561047437
        name: Enim consectetur sit omnis expedita.
        trackIDs:
        - 1854591721
        - 551277612
        - 1986047975
      - id: 561047437
        name: Enim consectetur sit omnis expedita.
        trackIDs:
        - 1854591721
        - 551277612
        - 1986047975
      - id: 561047437
        name: Enim consectetur sit omnis expedita.
        trackIDs:
        - 1854591721
        - 551277612
        - 1986047975
      total: 2061705486
    required:
    - total
    - resources
  AccountGetAccountPlaylistResponseBody:
    title: AccountGetAccountPlaylistResponseBody
    type: object
    properties:
      id:
        type: integer
        description: Playlist id
        example: 1602526843
        format: int32
      name:
        type: string
        description: Playlist name
        example: Aut omnis.
      trackIDs:
        type: array
        items:
          type: integer
          example: 96063473
          format: int32
        description: Array of TrackIDs
        example:
        - 22940470
        - 1098792220
        - 1974375732
        - 685223546
    example:
      id: 1229975513
      name: Vero ut optio possimus rem quisquam magnam.
      trackIDs:
      - 1511592164
      - 1452659032
      - 1737922438
    required:
    - id
    - name
    - trackIDs
  AccountLoginRequestBody:
    title: AccountLoginRequestBody
    type: object
    properties:
      email:
        type: string
        description: Email of the user
        example: Earum reprehenderit voluptatem rem sit voluptatum.
      password:
        type: string
        description: Password of the user
        example: Nulla velit totam excepturi.
    example:
      email: Eos non rem reprehenderit mollitia et asperiores.
      password: Vitae soluta sequi.
  AccountLoginResponseBody:
    title: AccountLoginResponseBody
    type: object
    properties:
      accountID:
        type: string
        description: User's role
        example: Qui ullam voluptas libero id est.
      email:
        type: string
        description: User's email
        example: Et culpa doloremque sint ex unde sequi.
      refresh_token:
        type: string
        description: Refresh token
        example: Eaque voluptas.
      role:
        type: string
        description: User's role
        example: Voluptas modi quo.
      token:
        type: string
        description: JWT Token
        example: Asperiores et eius ducimus.
    example:
      accountID: Est voluptate cumque et.
      email: Omnis est debitis ut aliquid iste.
      refresh_token: Ipsum suscipit.
      role: Nobis asperiores voluptate saepe ut omnis voluptatem.
      token: Deserunt similique aliquam consequatur ex ratione.
    required:
    - email
    - token
    - refresh_token
    - role
  AccountPlaylistResponseResponseBody:
    title: AccountPlaylistResponseResponseBody
    type: object
    properties:
      id:
        type: integer
        description: Playlist id
        example: 1291509483
        format: int32
      name:
        type: string
        description: Playlist name
        example: Ipsum repellat accusantium sed magnam aliquam fugiat.
      trackIDs:
        type: array
        items:
          type: integer
          example: 1628879251
          format: int32
        description: Array of TrackIDs
        example:
        - 1480810906
        - 1239063585
    example:
      id: 731017624
      name: Ratione suscipit culpa non architecto veniam neque.
      trackIDs:
      - 1898964902
      - 207730188
    required:
    - id
    - name
    - trackIDs
  AccountRegisterRequestBody:
    title: AccountRegisterRequestBody
    type: object
    properties:
      confirmedPassword:
        type: string
        description: Confirmed password of the user
        example: Et vitae dolore temporibus dolore.
      email:
        type: string
        description: Email of the user
        example: Asperiores est voluptatibus voluptas ut rem.
      firstName:
        type: string
        description: First name of the user
        example: Ut tempore a praesentium.
      lastName:
        type: string
        description: Last name of the user
        example: Accusamus occaecati velit.
      password:
        type: string
        description: Password of the user
        example: Voluptatem nisi assumenda consequatur nam.
    example:
      confirmedPassword: Atque est error voluptas dolorem.
      email: Aspernatur omnis.
      firstName: Delectus rerum veniam ipsam iste et.
      lastName: Maxime recusandae.
      password: Quia tempora a minima.
    required:
    - email
    - password
    - confirmedPassword
    - firstName
    - lastName
  AccountRegisterResponseBody:
    title: AccountRegisterResponseBody
    type: object
    properties:
      message:
        type: string
        description: Operation completion status
        example: Itaque qui nisi aut sapiente ut.
    example:
      message: Libero dolore aliquid.
    required:
    - message
  AccountRemoveTrackFromAccountPlaylistResponseBody:
    title: AccountRemoveTrackFromAccountPlaylistResponseBody
    type: object
    properties:
      message:
        type: string
        description: Operation completion status
        example: Illo libero et.
    example:
      message: Qui nemo aperiam.
    required:
    - message
