openapi: 3.0.3
info:
  title: Accounts Backend Service
  description: Microservice for account management & operations
  version: "1.0"
servers:
- url: http://localhost:80
  description: Default server for accounts
paths:
  /api/v1/account-service/accounts/login:
    post:
      tags:
      - account
      summary: login account
      operationId: account#login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequestBody'
            example:
              email: Iusto non mollitia qui non culpa laborum.
              password: Corrupti voluptas officia nostrum quia voluptatum.
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
              example:
                accountID: Ad quo et quasi sint accusamus.
                email: Tempora recusandae nobis.
                refresh_token: Molestias exercitationem molestias.
                role: In minus sint rerum.
                token: Reiciendis harum asperiores.
  /api/v1/account-service/accounts/register:
    post:
      tags:
      - account
      summary: register account
      operationId: account#register
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequestBody'
            example:
              confirmedPassword: Numquam quos excepturi vero ad est.
              email: Dolorum et labore cumque quisquam dolorem adipisci.
              firstName: Quibusdam omnis nemo provident eos quis ut.
              lastName: Ipsum et molestiae.
              password: Voluptates id recusandae temporibus et dolore.
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterResponse'
              example:
                message: Ab facilis odio facere et.
  /api/v1/account-service/playlists:
    get:
      tags:
      - playlist
      summary: getAccountPlaylistCollection playlist
      operationId: playlist#getAccountPlaylistCollection
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountPlaylistCollectionResponse'
              example:
                resources:
                - createdAt: Commodi id delectus dolor ex voluptatem eum.
                  id: 561047437
                  name: Enim consectetur sit omnis expedita.
                  trackIDs:
                  - 1854591721
                  - 551277612
                  - 1986047975
                - createdAt: Commodi id delectus dolor ex voluptatem eum.
                  id: 561047437
                  name: Enim consectetur sit omnis expedita.
                  trackIDs:
                  - 1854591721
                  - 551277612
                  - 1986047975
                - createdAt: Commodi id delectus dolor ex voluptatem eum.
                  id: 561047437
                  name: Enim consectetur sit omnis expedita.
                  trackIDs:
                  - 1854591721
                  - 551277612
                  - 1986047975
                total: 1198581461
    post:
      tags:
      - playlist
      summary: createAccountPlaylist playlist
      operationId: playlist#createAccountPlaylist
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAccountPlaylistRequestBody'
            example:
              name: Cum corporis autem repellendus.
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterResponse'
              example:
                message: Vel et est quasi unde odit sed.
  /api/v1/account-service/playlists/{playlistID}:
    delete:
      tags:
      - playlist
      summary: deleteAccountPlaylist playlist
      operationId: playlist#deleteAccountPlaylist
      parameters:
      - name: playlistID
        in: path
        required: true
        schema:
          type: integer
          example: 16861361778222263426
        example: 14645310068942176912
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterResponse'
              example:
                message: Aut accusamus sequi quae accusantium praesentium.
    get:
      tags:
      - playlist
      summary: getAccountPlaylist playlist
      operationId: playlist#getAccountPlaylist
      parameters:
      - name: playlistID
        in: path
        description: Playlist ID
        required: true
        schema:
          type: integer
          description: Playlist ID
          example: 5006136830838661682
        example: 17030425305822026802
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountPlaylistResponse'
              example:
                createdAt: Non praesentium quo molestiae.
                id: 2072942933
                name: Eos voluptas soluta.
                trackIDs:
                - 1564306613
                - 991115872
    put:
      tags:
      - playlist
      summary: renameAccountPlaylist playlist
      operationId: playlist#renameAccountPlaylist
      parameters:
      - name: playlistID
        in: path
        description: Playlist id to modify
        required: true
        schema:
          type: integer
          description: Playlist id to modify
          example: 5161714125584465614
        example: 5044420917136012476
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAccountPlaylistRequestBody'
            example:
              name: Voluptatem sequi adipisci iure dolorem nesciunt itaque.
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterResponse'
              example:
                message: Et eius minima quo.
  /api/v1/account-service/playlists/{playlistID}/tracks/{trackID}:
    delete:
      tags:
      - playlist
      summary: removeTrackFromAccountPlaylist playlist
      operationId: playlist#removeTrackFromAccountPlaylist
      parameters:
      - name: playlistID
        in: path
        description: Playlist ID to modify
        required: true
        schema:
          type: integer
          description: Playlist ID to modify
          example: 15270916825326370212
        example: 9926222968472046256
      - name: trackID
        in: path
        description: Track ID to be deleted
        required: true
        schema:
          type: integer
          description: Track ID to be deleted
          example: 14460278771394442867
        example: 16216240333212018809
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterResponse'
              example:
                message: A praesentium rerum accusamus occaecati velit et.
    post:
      tags:
      - playlist
      summary: addTrackToAccountPlaylist playlist
      operationId: playlist#addTrackToAccountPlaylist
      parameters:
      - name: playlistID
        in: path
        description: Playlist ID to modify
        required: true
        schema:
          type: integer
          description: Playlist ID to modify
          example: 3635217761166779233
        example: 4929482363712135635
      - name: trackID
        in: path
        description: Track ID to be added
        required: true
        schema:
          type: integer
          description: Track ID to be added
          example: 16140602761404116407
        example: 8273025523250330751
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterResponse'
              example:
                message: Ea nostrum nemo itaque.
components:
  schemas:
    AccountPlaylistCollectionResponse:
      type: object
      properties:
        resources:
          type: array
          items:
            $ref: '#/components/schemas/AccountPlaylistResponse'
          description: Operation completion status
          example:
          - createdAt: Commodi id delectus dolor ex voluptatem eum.
            id: 561047437
            name: Enim consectetur sit omnis expedita.
            trackIDs:
            - 1854591721
            - 551277612
            - 1986047975
          - createdAt: Commodi id delectus dolor ex voluptatem eum.
            id: 561047437
            name: Enim consectetur sit omnis expedita.
            trackIDs:
            - 1854591721
            - 551277612
            - 1986047975
        total:
          type: integer
          description: Number of resources
          example: 333424829
          format: int32
      example:
        resources:
        - createdAt: Commodi id delectus dolor ex voluptatem eum.
          id: 561047437
          name: Enim consectetur sit omnis expedita.
          trackIDs:
          - 1854591721
          - 551277612
          - 1986047975
        - createdAt: Commodi id delectus dolor ex voluptatem eum.
          id: 561047437
          name: Enim consectetur sit omnis expedita.
          trackIDs:
          - 1854591721
          - 551277612
          - 1986047975
        - createdAt: Commodi id delectus dolor ex voluptatem eum.
          id: 561047437
          name: Enim consectetur sit omnis expedita.
          trackIDs:
          - 1854591721
          - 551277612
          - 1986047975
        total: 1675693190
      required:
      - total
      - resources
    AccountPlaylistResponse:
      type: object
      properties:
        createdAt:
          type: string
          description: Time of creation
          example: Iure voluptates.
        id:
          type: integer
          description: Playlist id
          example: 893323924
          format: int32
        name:
          type: string
          description: Playlist name
          example: Fuga dolorem non iure tenetur.
        trackIDs:
          type: array
          items:
            type: integer
            example: 363905427
            format: int32
          description: Array of TrackIDs
          example:
          - 317328226
          - 1842496594
      example:
        createdAt: Et illo.
        id: 1491752593
        name: Animi fugiat rerum rerum vel.
        trackIDs:
        - 760748099
        - 746536461
        - 2079806465
        - 1404166017
      required:
      - id
      - name
      - trackIDs
    CreateAccountPlaylistRequestBody:
      type: object
      properties:
        name:
          type: string
          description: Playlist name
          example: Laudantium quis harum reprehenderit.
      example:
        name: Maiores repudiandae eos.
      required:
      - name
    LoginRequestBody:
      type: object
      properties:
        email:
          type: string
          description: Email of the user
          example: Ipsa quae.
        password:
          type: string
          description: Password of the user
          example: Recusandae excepturi deserunt.
      example:
        email: Sapiente doloribus consectetur corporis doloribus.
        password: Et ipsa accusantium molestiae.
      required:
      - email
      - password
    LoginResponse:
      type: object
      properties:
        accountID:
          type: string
          description: User's role
          example: Aut ut adipisci molestiae.
        email:
          type: string
          description: User's email
          example: Asperiores incidunt.
        refresh_token:
          type: string
          description: Refresh token
          example: Omnis beatae.
        role:
          type: string
          description: User's role
          example: Explicabo at et dolor sed.
        token:
          type: string
          description: JWT Token
          example: Perspiciatis itaque totam.
      example:
        accountID: Quisquam non accusamus ut iste.
        email: Amet id et voluptas.
        refresh_token: Soluta pariatur inventore ad minima dolorum.
        role: Non id.
        token: Qui sequi quia voluptas dolorem minima.
      required:
      - email
      - token
      - refresh_token
      - role
    RegisterRequestBody:
      type: object
      properties:
        confirmedPassword:
          type: string
          description: Confirmed password of the user
          example: Voluptatem nisi molestias consequatur quae.
        email:
          type: string
          description: Email of the user
          example: Animi architecto est perferendis ratione ut.
        firstName:
          type: string
          description: First name of the user
          example: Nemo dolore dolor impedit explicabo.
        lastName:
          type: string
          description: Last name of the user
          example: Excepturi et alias non sed quam.
        password:
          type: string
          description: Password of the user
          example: Qui ut.
      example:
        confirmedPassword: Commodi ut.
        email: Qui consectetur blanditiis nesciunt unde itaque.
        firstName: Debitis similique iure.
        lastName: Et molestiae expedita explicabo ut.
        password: Aperiam officia rem.
      required:
      - email
      - password
      - confirmedPassword
      - firstName
      - lastName
    RegisterResponse:
      type: object
      properties:
        message:
          type: string
          description: Operation completion status
          example: Enim aut itaque eveniet consequatur.
      example:
        message: Commodi iste delectus.
      required:
      - message
tags:
- name: swagger
- name: account
  description: Account operations
- name: playlist
  description: Playlist operations
